export function StyledCheckbox() {
  return (
    <label
      className="
    relative
    flex
    cursor-pointer
    items-center    
    "
    >
      <input
        type="checkbox"
        className="
              before:content['']
              h-[14px]              
              w-[14px]
              cursor-pointer
              appearance-none
              rounded-sm
              border 
              border-rose-200
              transition-all
              duration-100
              checked:border-rose-300
              checked:bg-rose-600 
              checked:before:bg-rose-200 
              hover:before:opacity-10
              "
        id="checkbox"
      ></input>
    </label>
  );
}
